insert into grocery_list (department, quantity, item)
values ('dairy', '1', 'american cheese'),
       ('dairy', '1', 'milk'),
       ('dairy', '1', 'eggs'),
       ('household', '1', 'toilet paper'),
       ('household', '1', 'dish soap'),
       ('Baking', '1', 'flour'),
       ('world_foods', '1', 'pasta'),
       ('world_foods', '1', 'ramen'),
       ('world_foods', '1', 'rice'),
       ('world_foods', '1', 'kewpie'),
       ('world_foods', '1', 'sauce'),
       ('shelf_stable', '1', 'mustard'),
       ('breakfast', '1', 'coffee'),
       ('breakfast', '1', 'cereal'),
       ('meat', '3lb', 'chicken breast'),
       ('vegetables', '3', 'onioin'),
       ('vegetables', '1', 'garlic'),
       ('vegetables', '1', 'broccoli'),
       ('vegetables', '2', 'carrot'),
       ('vegetables', '2lb', 'potato'),
       ('vegetables', '8oz', 'mushrooms'),
       ('fruits', '1', 'banana'),
       ('fruits', '1', 'berries'),
       ('deli', '1/2', 'turkey'),
       ('deli', '1/2', 'swiss'),
       ('deli', '1', 'ham');
update grocery_list
set department = UPPER(department);
